var list1 = [
{list:"1",
id:"1",
idCondition:"1-R",
orientation:"R",
speakerGender:"Female",
speakerName:"Linda",
topic:"global warming",
complement:"global warming is solely the effect of natural causes",
complementType:"concrete"},
 {list:"1",
id:"2",
idCondition:"2-L",
orientation:"L",
speakerGender:"Male",
speakerName:"Rob",
topic:"healthcare",
complement:"the government should run the healthcare system",
complementType:"abstract-should"},
 {list:"1",
id:"3",
idCondition:"3-R",
orientation:"R",
speakerGender:"Female",
speakerName:"Katie",
topic:"minimum wage",
complement:"the minimum wage hurts small businesses",
complementType:"concrete"},
 {list:"1",
id:"4",
idCondition:"4-L",
orientation:"L",
speakerGender:"Male",
speakerName:"Luke",
topic:"gay marriage",
complement:"same-sex couples should be allowed to marry",
complementType:"abstract-should"},
 {list:"1",
id:"5",
idCondition:"5-R",
orientation:"R",
speakerGender:"Female",
speakerName:"Mary",
topic:"the wall",
complement:"the government should fund the border wall",
complementType:"abstract-should"},
 {list:"1",
id:"6",
idCondition:"6-L",
orientation:"L",
speakerGender:"Male",
speakerName:"Brian",
topic:"gun laws",
complement:"strict gun control laws prevent mass shootings",
complementType:"concrete"},
 {list:"1",
id:"7",
idCondition:"7-R",
orientation:"R",
speakerGender:"Female",
speakerName:"Cindy",
topic:"Obama",
complement:"Obama damaged the American economy",
complementType:"concrete"},
 {list:"1",
id:"8",
idCondition:"8-L",
orientation:"L",
speakerGender:"Male",
speakerName:"Derek",
topic:"abortion",
complement:"abortion rights should be expanded",
complementType:"abstract-should"},
 {list:"1",
id:"9",
idCondition:"9-R",
orientation:"R",
speakerGender:"Female",
speakerName:"Maria",
topic:"affirmative action",
complement:"affirmative action programs drain government resources",
complementType:"concrete"},
 {list:"1",
id:"10",
idCondition:"10-L",
orientation:"L",
speakerGender:"Male",
speakerName:"Fred",
topic:"capital punishment",
complement:"the federal government should ban capital punishment",
complementType:"abstract"},
 {list:"1",
id:"11",
idCondition:"11-R",
orientation:"R",
speakerGender:"Female",
speakerName:"Allison",
topic:"Trump",
complement:"Trump\'s national security policies make Americans safer",
complementType:"concrete"},
 {list:"1",
id:"12",
idCondition:"12-L",
orientation:"L",
speakerGender:"Male",
speakerName:"Mike",
topic:"corporate taxes",
complement:"high corporate taxes help the American economy",
complementType:"concrete"},
 {list:"1",
id:"13",
idCondition:"13-R",
orientation:"R",
speakerGender:"Female",
speakerName:"Sandra",
topic:"environmental laws",
complement:"there are too many environmental laws",
complementType:"abstract"},
 {list:"1",
id:"14",
idCondition:"14-L",
orientation:"L",
speakerGender:"Male",
speakerName:"David",
topic:"medicaid",
complement:"medicaid funding should be increased",
complementType:"abstract-should"},
 {list:"1",
id:"15",
idCondition:"15-R",
orientation:"R",
speakerGender:"Female",
speakerName:"Erin",
topic:"guns and teachers",
complement:"schoolteachers carrying guns promotes student safety",
complementType:"concrete"},
 {list:"1",
id:"16",
idCondition:"16-L",
orientation:"L",
speakerGender:"Male",
speakerName:"Jeff",
topic:"immigration",
complement:"immigrants support the American economy",
complementType:"concrete"},
 {list:"1",
id:"17",
idCondition:"17-R",
orientation:"R",
speakerGender:"Male",
speakerName:"Steve",
topic:"abortion-2",
complement:"abortion is unethical",
complementType:"not sure"},
 {list:"1",
id:"filler1",
idCondition:"filler1-Y",
orientation:"",
speakerGender:"Female",
speakerName:"Rita",
topic:"elections",
complement:"US presidential elections are held in November",
complementType:"NONE"},
 {list:"1",
id:"filler2",
idCondition:"filler-N",
orientation:"",
speakerGender:"Male",
speakerName:"Daniel",
topic:"capital",
complement:"the capital of the US is in Ohio",
complementType:"NONE"}
];

var list2 = [
{list:"2",
id:"1",
idCondition:"1-L",
orientation:"L",
speakerGender:"Female",
speakerName:"Linda",
topic:"global warming",
complement:"global warming is solely the effect of human actions",
complementType:"concrete"},
 {list:"2",
id:"2",
idCondition:"2-R",
orientation:"R",
speakerGender:"Male",
speakerName:"Rob",
topic:"healthcare",
complement:"the government should stay out of the healthcare system",
complementType:"abstract-should"},
 {list:"2",
id:"3",
idCondition:"3-L",
orientation:"L",
speakerGender:"Female",
speakerName:"Katie",
topic:"minimum wage",
complement:"the minimum wage ensures fair pay",
complementType:"concrete"},
 {list:"2",
id:"4",
idCondition:"4-R",
orientation:"R",
speakerGender:"Male",
speakerName:"Luke",
topic:"gay marriage",
complement:"only heterosexual couples should be allowed to marry",
complementType:"abstract-should"},
 {list:"2",
id:"5",
idCondition:"5-L",
orientation:"L",
speakerGender:"Female",
speakerName:"Mary",
topic:"the wall",
complement:"the government should refuse to fund the border wall",
complementType:"abstract-should"},
 {list:"2",
id:"6",
idCondition:"6-R",
orientation:"R",
speakerGender:"Male",
speakerName:"Brian",
topic:"gun laws",
complement:"strict gun control laws cause mass shootings",
complementType:"concrete"},
 {list:"2",
id:"7",
idCondition:"7-L",
orientation:"L",
speakerGender:"Female",
speakerName:"Cindy",
topic:"Obama",
complement:"Obama improved the American economy",
complementType:"concrete"},
 {list:"2",
id:"8",
idCondition:"8-R",
orientation:"R",
speakerGender:"Male",
speakerName:"Derek",
topic:"abortion",
complement:"abortion rights should be reduced",
complementType:"abstract-should"},
 {list:"2",
id:"9",
idCondition:"9-L",
orientation:"L",
speakerGender:"Female",
speakerName:"Maria",
topic:"affirmative action",
complement:"affirmative action programs ensure equal access to jobs",
complementType:"concrete"},
 {list:"2",
id:"10",
idCondition:"10-R",
orientation:"R",
speakerGender:"Male",
speakerName:"Fred",
topic:"capital punishment",
complement:"all states should allow capital punishment",
complementType:"abstract"},
 {list:"2",
id:"11",
idCondition:"11-L",
orientation:"L",
speakerGender:"Female",
speakerName:"Allison",
topic:"Trump",
complement:"Trump\'s national security policies put Americans in danger",
complementType:"concrete"},
 {list:"2",
id:"12",
idCondition:"12-R",
orientation:"R",
speakerGender:"Male",
speakerName:"Mike",
topic:"corporate taxes",
complement:"high corporate taxes hurt the American economy",
complementType:"concrete"},
 {list:"2",
id:"13",
idCondition:"13-L",
orientation:"L",
speakerGender:"Female",
speakerName:"Sandra",
topic:"environmental laws",
complement:"there are too few environmental laws",
complementType:"abstract"},
 {list:"2",
id:"14",
idCondition:"14-R",
orientation:"R",
speakerGender:"Male",
speakerName:"David",
topic:"medicaid",
complement:"medicaid funding should be decreased",
complementType:"abstract-should"},
 {list:"2",
id:"15",
idCondition:"15-L",
orientation:"L",
speakerGender:"Female",
speakerName:"Erin",
topic:"guns and teachers",
complement:"schoolteachers carrying guns threatens student safety",
complementType:"concrete"},
 {list:"2",
id:"16",
idCondition:"16-R",
orientation:"R",
speakerGender:"Male",
speakerName:"Jeff",
topic:"immigration",
complement:"immigrants steal jobs from Americans",
complementType:"concrete"},
 {list:"2",
id:"17",
idCondition:"17-L",
orientation:"L",
speakerGender:"Male",
speakerName:"Steve",
topic:"abortion-2",
complement:"abortion is a woman\'s right",
complementType:"not sure"},
 {list:"2",
id:"filler1",
idCondition:"filler1-Y",
orientation:"",
speakerGender:"Female",
speakerName:"Rita",
topic:"elections",
complement:"US presidential elections are held in November",
complementType:"NONE"},
 {list:"2",
id:"filler2",
idCondition:"filler-N",
orientation:"",
speakerGender:"Male",
speakerName:"Daniel",
topic:"capital",
complement:"the capital of the US is in Ohio",
complementType:"NONE"}
];